version: "3.8"

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - .:/var/www
      - ./docker/nginx/logs:/var/log/nginx/

  mysql:
    image: library/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
    #- ./docker/mysql/my.cnf:/etc/mysql/my.cnf